config/routes.rb
Rails.application.routes.draw do

  resources :template_fields
  resources :templates

  resources :polls 
  resources :categories do
    resources :questions
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  belongs_to :poll, optional: true
  has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions
end

app/models/formbuilder.rb
class Formbuilder < ApplicationRecord
  has_many :formquestions, :dependent => :destroy
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :categories, :dependent => :destroy
  accepts_nested_attributes_for :categories
  after_commit :calculate_score_result, on: [:create, :update]

  def self.get_attributes_from_template(poll)
    poll.update_attributes(score_init: Template.sum(:score), name: "P#{Time.now.strftime("%d%m%H%M%S")}")
    Template.all.each do |cat|
      if cat.score != 0
        category = poll.categories.new(name: cat.category, score_init: cat.score )
          cat.template_fields.each do |quest|
            category.questions.new(content: quest.question, score_init: quest.score)
          end
      end
    end
  end

  def calculate_score_result
    categories.each {|q| q.update!(score_result: q.questions.sum(:score_result))}
    update_attribute :score_result, categories.sum(:score_result)
  end
  
end

app/models/question.rb
class Question < ApplicationRecord
  validates :score_result, presence: true, numericality: { only_integer: true }
  validates :content, presence: true
  belongs_to :category, optional: true
end

app/models/store.rb
class Store < ApplicationRecord
end

app/models/template.rb
class Template < ApplicationRecord
  validates :category, presence: true
  has_many :template_fields, :dependent => :destroy
  accepts_nested_attributes_for :template_fields, :reject_if => lambda { |a| a[:question].blank? && a[:score].blank? }, :allow_destroy => true

  after_commit :calculate_score_init, on: [:create, :update]

  def calculate_score_init
    update_attribute :score, template_fields.sum(:score)
  end

end

app/models/template_field.rb
class TemplateField < ApplicationRecord
  validates :question, presence: true
  validates :score, presence: true, length: { in: 1..2 }
  belongs_to :template, optional: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :encryptable, :authentication_keys => [:login]

  after_initialize :create_login, :if => :new_record?
  attr_accessor :login


  def create_login
    if self.username.blank?
      email = self.email.split(/@/)
      login_taken = User.where(:username => email[0]).first
      unless login_taken
        self.username = email[0]
      else
        self.username = self.email
      end
    end
  end


  private

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", {:value => login.downcase}]).first
    else
      where(conditions.to_h).first
    end
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def rate_to_percent(rate, score)
    if rate != 0
      result = (rate.to_f / score.to_f * 100).round
    end
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', id: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/content_helper.rb
module ContentHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/formbuilders_helper.rb
module FormbuildersHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saop</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/templates/_form.html.erb
<%= form_for(template, html: { class: "form-horizontal" }) do |f| %>
  <% if template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h2>
      <ul>
      <% template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-xs-4">
      <%= f.label :category %>
      <%= f.text_field :category, class: "form-control" %> <br />
    </div>
  </div>

          <%= f.fields_for :template_fields do |builder| %>
          <%= render "template_field_fields", f: builder %>
          <% end %>
          <%= link_to_add_fields "Add Question", f, :template_fields %><p />
        <div class="form-group">
          <%= f.submit "Save", class: "btn btn-info" %>
        </div>
<% end %>

app/views/templates/_form_template_fields.html.erb
<p />
<div class="row">
  <div class="form-group">
      <div class="col-xs-10 col-sm-5 col-md-3">
        <%= f.text_area :question, class: "form-control", placeholder: "Question here" %>
      </div>
    </div>
</div>
<div class="row">
    <div class="form-group">
      <div class="col-xs-6 col-sm-3 col-md-2">
          <%= f.select(:score, (0..2), {include_blank: "Select rate"}, {class: 'form-control', id: "textarea"} )%>
      </div>
      <div class="col-xs-2 col-sm-1 col-md-1">
          <%= f.link_to_remove "remove", class: "btn btn-danger" %>
      </div>
    </div>
</div>

app/views/templates/_template_field_fields.html.erb
<p />
<fieldset>
<div class="row">

  <div class="form-group">
      <div class="col-xs-10 col-sm-5 col-md-3">
        <%= f.text_area :question, class: "form-control", placeholder: "Question here", id: "placeholder" %>
      </div>
    </div>
</div>
<div class="row">
    <div class="form-group">
      <div class="col-xs-6 col-sm-3 col-md-2">
          <%= f.select(:score, (1..2), {include_blank: "Select rate"}, {class: 'form-control', id: "select"} )%>
      </div>
      <div class="col-xs-2 col-sm-1 col-md-1">
          <%= f.hidden_field :_destroy %>
          <%= link_to "remove", '#', id: "remove_fields" %>
      </div>
    </div>
</div>
</fieldset>

app/views/templates/edit.html.erb
<div class="col-xs-12">
  <h1>Editing Template</h1>

  <%= render 'form', template: @template %>
</div>

<div class="rows">
  <%= link_to 'Show', @template %> |
  <%= link_to 'Back', templates_path %>
</div>

app/views/templates/index.html.erb
<div class="rows">
<div class="col-xs-10">
  <p id="notice"><%= notice %></p>

<h1>Templates</h1>

<table  class="table table-bordered">
  <thead>
    <tr>
      <th>Category</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.category %></td>
        <td><%= template.score %></td>
        <td><%= link_to 'Show', template %> |
            <%= link_to 'Edit', edit_template_path(template) %> |
            <%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Template', new_template_path %>
</div>
</div>

app/views/templates/new.html.erb
<div class="col-xs-12">
<h1>New Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Back', templates_path %>
</div>

app/views/templates/show.html.erb
<div class="col-xs-12">
  <p id="notice"><%= notice %></p>
  <legend>
    <h2>Category details</h2>
        <p>Name: <small><%=@template.category %></small></p>
        <p>Name: <small><%=@template.score %></small></p>
  </legend>
  <div class="col-xs-9">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Question</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
          <% @template.template_fields.each do |i| %>
        <tr>
          <td><%= i.question %></td>
          <td><%= i.score %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Edit', edit_template_path(@template) %> |
    <%= link_to 'Back', templates_path %>
  </div>
</div>