config/routes.rb
Rails.application.routes.draw do

  resources :template_fields
  resources :templates

  resources :polls 
  resources :categories do
    resources :questions
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  belongs_to :poll, optional: true
  has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions
end

app/models/formbuilder.rb
class Formbuilder < ApplicationRecord
  has_many :formquestions, :dependent => :destroy
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :categories, :dependent => :destroy
  accepts_nested_attributes_for :categories
  after_commit :calculate_score_result, on: [:create, :update]

  def self.get_attributes_from_template(poll)
    poll.update_attributes(score_init: Template.sum(:score), name: "P#{Time.now.strftime("%d%m%H%M%S")}")
    Template.all.each do |cat|
      if cat.score != 0
        category = poll.categories.new(name: cat.category, score_init: cat.score )
          cat.template_fields.each do |quest|
            category.questions.new(content: quest.question, score_init: quest.score)
          end
      end
    end
  end

  def calculate_score_result
    categories.each {|q| q.update!(score_result: q.questions.sum(:score_result))}
    update_attribute :score_result, categories.sum(:score_result)
  end
  
end

app/models/question.rb
class Question < ApplicationRecord
  validates :score_result, presence: true, numericality: { only_integer: true }
  validates :content, presence: true
  belongs_to :category, optional: true
end

app/models/store.rb
class Store < ApplicationRecord
end

app/models/template.rb
class Template < ApplicationRecord
  validates :category, presence: true
  has_many :template_fields, :dependent => :destroy
  accepts_nested_attributes_for :template_fields, :reject_if => lambda { |a| a[:question].blank? && a[:score].blank? }, :allow_destroy => true

  after_commit :calculate_score_init, on: [:create, :update]

  def calculate_score_init
    update_attribute :score, template_fields.sum(:score)
  end

end

app/models/template_field.rb
class TemplateField < ApplicationRecord
  validates :question, presence: true
  validates :score, presence: true, length: { in: 1..2 }
  belongs_to :template, optional: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :encryptable, :authentication_keys => [:login]

  after_initialize :create_login, :if => :new_record?
  attr_accessor :login


  def create_login
    if self.username.blank?
      email = self.email.split(/@/)
      login_taken = User.where(:username => email[0]).first
      unless login_taken
        self.username = email[0]
      else
        self.username = self.email
      end
    end
  end


  private

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", {:value => login.downcase}]).first
    else
      where(conditions.to_h).first
    end
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  def show
  end

  # GET /polls/new

  def new
    @poll = Poll.new
    Poll.get_attributes_from_template(@poll)
  end

  # GET /polls/1/edit
  def edit
    # binding.pry
  end

  # POST /polls
  def create
    @poll = Poll.new(poll_params)
       binding.pry
    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /polls/1
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /polls/1
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:name, :score_init,
          categories_attributes: [ :name, :score_init, :id,
                    questions_attributes: [:content, :id, :score_result, :comment, :score_init]])
    end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]


  def index
    @stores = Store.all
  end


  def show
  end

  def new
    @store = Store.new
  end

  def edit
  end


  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Вы успешно добавили магазин.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Вы успешно обновили информацию о магазине.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Вы успешно удалили магазин.' }
      format.json { head :no_content }
    end
  end

  private

    def set_store
      @store = Store.find(params[:id])
    end

    def store_params
      params.require(:store).permit(:store_name, :store_adress, :store_caregory)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #def new
  #  @user = User.new
  #end
  #def create
  #  @user = User.new(user_params)
  #  if @user.save
  #    flash.now[:notice] = "You signed up successfully"
  #    flash.now[:color]= "valid"
  #  else
  #    flash.now[:notice] = "Form is invalid"
  #    flash.now[:color]= "invalid"
  #  end
  #  render "new"
  #end

  #private

 # def user_params
  #  params.require(:user).permit(:email, :password, :password_confirmation)
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def rate_to_percent(rate, score)
    if rate != 0
      result = (rate.to_f / score.to_f * 100).round
    end
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', id: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/content_helper.rb
module ContentHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/formbuilders_helper.rb
module FormbuildersHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/polls/_categories_fields.html.erb
<div class="form-group">
  <div class="col-sm-4">
    <legend><%= f.object[:name] %></legend>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :score_init%>
  </div>
</div>
<div class="form-group">
    <%= f.fields_for :questions do |builder| %>
      <%= render 'question_fields', :f => builder %>
    <% end %>
</div>

app/views/polls/_form.html.erb
<div class="rows">
<%= form_for(poll, html: { class: "form-horizontal" }) do |f| %>
  <% if poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>
      <ul>
      <% poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <p><%= poll.name %></p>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :score_init %>
        <%= f.fields_for :categories do |builder| %>
            <%= render "categories_fields", :f => builder %>
        <% end %>
    <div class="form-group">
      <%= f.submit "Save", class: "btn btn-default" %>
    </div>
<% end %>
</div>

app/views/polls/_question_fields.html.erb
<div class="list-group">
  <div class="form-group">
      <div class="col-sm-4">
      <label class="list-group-item list-group-item-info"><%= f.object[:content] %></label>
          <%= f.hidden_field :content%>
          <%= f.hidden_field :score_init%>
          <%= f.select(:score_result, 0..f.object[:score_init],  {include_blank: "Select rate"}, {class: 'form-control'} ) %>
      </div>
  </div>
  <div class="form-group">
      <div class="col-sm-4">
        <%= f.text_area :comment, class: "form-control"  %>
      </div>
  </div>
</div>

app/views/polls/edit.html.erb
<div class="col-xs-12">
  <h1>Editing Poll</h1>
  <%= render 'form', poll: @poll %>
</div>
<div class="rows">
  <%= link_to 'Show', @poll %> |
  <%= link_to 'Back', polls_path %>
</div>

app/views/polls/index.html.erb
<div class="col-xs-12">
  <p id="notice"><%= notice %></p>
  <h1>Polls</h1>
    <%if @polls.exists?%>
    <table class="table table-striped">
      <thead>
        <tr>
          <th >Poll name</th>
          <th>Pole rate</th>
          <th>Category rate</td>
        </tr>
      </thead>
      <tbody>
        <% @polls.each do |poll| %>
          <tr>
            <td><%= poll.name %></td>
            <td><strong><%= rate_to_percent(poll.score_result, poll.score_init) %>%</strong></td>
            <td>
              <% poll.categories.each do |cat| %>
              <%= cat.name %>
                <strong><%= rate_to_percent(cat.score_result, cat.score_init) %>%</strong> |
              <% end %>
            </td>
            <td><%= link_to 'Show', poll %> |
            <%= link_to 'Edit', edit_poll_path(poll) %> |
            <%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
    <% end %>
    </tbody>
  </table>
    <% end %>

      <%= link_to 'New Poll', new_poll_path %>
</div>

app/views/polls/new.html.erb
<div class="col-xs-12">
  <h1>New Poll</h1>
  <%= render 'form', poll: @poll %>
  <%= link_to 'Back', polls_path %>
</div>

app/views/polls/show.html.erb
<div class="col-xs-12">
  <p id="notice"><%= notice %></p>
  <legend>
    <h2>Shop POS and Business quality checklist</h2>
    <p>Doc Id: <small><%= @poll.id %></small></p>
    <p>Date: <small><%= @poll.created_at.strftime("%d.%m.%Y. %H:%M:%S") %></small></p>
    <p>Poll rate: <small><%= rate_to_percent(@poll.score_result, @poll.score_init) %>%</small></p>
  </legend>
  <div class="col-xs-9">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Quality and Excellence</th>
          <th>Evaluating method</th>
          <th>Rate</th>
          <th>Comment</th>
        </tr>
      </thead>
      <tbody>
          <% @poll.categories.each do |cat| %>
        <tr>
          <td><b><%= cat.name %></b></td>
          <td><b>Score: <%= cat.score_init %></b></td>
          <td><b>Rate: <%= cat.score_result %></b></td>
          <td><b><%= rate_to_percent(cat.score_result, cat.score_init) %>%</b></td>
        </tr>
            <% cat.questions.each do |question| %>
        <tr>
          <td><%= question.content %></td>
          <td>0-<%= question.score_init %></td>
          <td><%= question.score_result %></td>
          <td><%= question.comment %></td>
        </tr>
            <% end %>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Edit', edit_poll_path(@poll) %> |
    <%= link_to 'Back', polls_path %>
  </div>
</div>

app/views/stores/_form.html.erb
<%= form_for(store) do |f| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Название магазина" %>
    <%= f.text_field :store_name %>
  </div>

  <div class="field">
    <%= f.label "Адрес магазина" %>
    <%= f.text_field :store_adress %>
  </div>

  <div class="field">
    <%= f.label "Категория магазина" %>
    <%= f.text_field :store_caregory %>
  </div>

  <div class="actions">
  <%= f.submit "Создать магазин"%>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Редактировать магазин</h1>

<%= render 'form', store: @store %>

<%= link_to 'Показать', @store %> |
<%= link_to 'Вернуться', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список магазинов</h1>

<table border="1">
  <thead>
    <tr>
      <th>Название маазина</th>
      <th>Адрес магазина</th>
      <th>Категория магазина</th>
      <th colspan="3">Действия</th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr class=<%= cycle('even', 'odd') %>>
        <td><%= store.store_name %></td>
        <td><%= store.store_adress %></td>
        <td><%= store.store_caregory %></td>
        <td><%= link_to 'Показать', store %></td>
        <td><%= link_to 'Редактировать', edit_store_path(store) %></td>
        <td><%= link_to 'удалить', store, method: :delete, data: { confirm: 'Вы уверены, что хотите удалить магазин?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Создать новый магазин', new_store_path %>

app/views/stores/new.html.erb
<h1>Новый магазин</h1>

<%= render 'form', store: @store %>

<%= link_to 'вернуться', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название магазина:</strong>
  <%= @store.store_name %>
</p>

<p>
  <strong>Адрес магазина:</strong>
  <%= @store.store_adress %>
</p>

<p>
  <strong>Категория магазина:</strong>
  <%= @store.store_caregory %>
</p>

<%= link_to 'Редактировать', edit_store_path(@store) %> |
<%= link_to 'Вернуться', stores_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>